CREATE TABLE LEVEL (
LEVEL_ID INTEGER(10) NOT NULL,
LEVEL_NAME VARCHAR(255),
NO_OF_SEATS INTEGER(10)
);
CREATE TABLE SEAT(
SEAT_NO INTEGER(10) NOT NULL,
CUSTOMER_EMAIL_ID VARCHAR(255),
LEVEL_ID INTEGER(10),
SEAT_HOLD_ID INTEGER(10),
SEAT_STATUS INTEGER(10)
);
CREATE TABLE SEAT_HOLD(
SEAT_HOLD_ID bigint auto_increment,
CUSTOMER_EMAIL_ID VARCHAR(255),
SEAT_HOLD_TIME TIMESTAMP(23,10)
);
