INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (61,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (62,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (63,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (64,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (65,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (66,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (67,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (68,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (69,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (70,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (71,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (72,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (73,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (74,'',4,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (75,'',4,-1,2);
