INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (1,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (2,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (3,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (4,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (5,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (6,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (7,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (8,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (9,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (10,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (11,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (12,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (13,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (14,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (15,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (16,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (17,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (18,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (19,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (20,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (21,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (22,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (23,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (24,'',1,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (25,'',1,-1,2);
