INSERT INTO LEVEL(LEVEL_ID,LEVEL_NAME,NO_OF_SEATS)
VALUES (1,'BALCONY2', 25);
INSERT INTO LEVEL(LEVEL_ID,LEVEL_NAME,NO_OF_SEATS)
VALUES (2,'BALCONY1', 20);
INSERT INTO LEVEL(LEVEL_ID,LEVEL_NAME,NO_OF_SEATS)
VALUES (3,'MAIN', 15);
INSERT INTO LEVEL(LEVEL_ID,LEVEL_NAME,NO_OF_SEATS)
VALUES (4,'ORCHERSTRA', 15);
