INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (46,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (47,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (48,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (49,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (50,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (51,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (52,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (53,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (54,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (55,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (56,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (57,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (58,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (59,'',3,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (60,'',3,-1,2);