INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (26,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (27,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (28,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (29,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (30,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (31,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (32,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (33,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (34,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (35,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (36,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (37,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (38,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (39,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (40,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (41,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (42,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (43,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (44,'',2,-1,2);
INSERT INTO SEAT(SEAT_NO,CUSTOMER_EMAIL_ID,LEVEL_ID,SEAT_HOLD_ID,SEAT_STATUS)
VALUES (45,'',2,-1,2);
